# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40ef9a5a0ed683cd085ab1d807e180f01f3cff55a3f8a789d8fdb7a74f3e06d4af76f33bb59f78763f079176ea076c744442a644d645beb65a15cab52a940e3a

test:
  secret_key_base: edd5e7e43c54c5f8f956eeb52795efe2f60e872fe5f0691b4031684cc64af02afdeb478493c29d13501d6b4a8a569e1241dc3a9a4723542a21c3ebd2fb93729f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
